### ISSUE TITLE
Add python 3 compatibility

### ISSUE THREAD

**Issue by AnnabellaRenee87** [eyal0/OctoPrint-MultipleUpload#3]
Can python 3 compatibility be added?

**Comment by eyal0** [comment]
Okay, I made a new release.  Let me know if that works.

**Comment by AnnabellaRenee87** [comment]
Got the update but it's getting flagged by Python 3 checker.

https://plugins.octoprint.org/plugins/Python3PluginCompatibilityCheck/

**Comment by Renaud11232** [comment]
Hello,
If there are no issue with the plugin and python 3, you should also update the plugin repository with:

```yml
compatibility:
  python: ">=2.7,<4"
```

This is probably why it got flagged

**Comment by eyal0** [comment]
Does the attached PR look right?

**Comment by Renaud11232** [comment]
Looks good to me

**Comment by Renaud11232** [comment]
Good news:
* I can find it and install the plugin through the Plugin Manager on py3
* It's not flagged anymore by the python 3 checker plugin
* It seems to be working fine so far

**Comment by Renaud11232** [comment]
You can probably close #4 as well :)
